Ricochet-Exchange/ricochet-frontend

- src/App.js
> Approve Subscription Button

- package.json
- src/components/layout/PanelChange/styles.module.scss
- src/constants/flowConfig.ts
I also re-added lint command. Useful to keep code clean and saves time.
> Fix in flowConfig

- src/containers/main/InvestContainer/index.tsx
Fix issue #58 
Searching for REX does not find anything
> Fix issue #58 Searching for Rex

- src/api/ethereum.ts
Fix #24 Set default gas price to 35 gwei for upgrade, downgrade, and approve tx
> Increase default gas price to fix #24

- src/components/layout/Banner/index.tsx
- src/components/layout/Banner/styles.module.scss
- src/containers/app/App.tsx
- src/containers/main/InvestContainer/index.tsx
- src/containers/main/InvestContainer/styles.module.scss
- src/i18n/en/main.json
Add header banner (unaudited) and footer banner (ricochet fee) to solve #31
> Add header banner (unaudited) and footer banner (ricochet fee) to solve #31

- src/components/layout/PanelChange/index.tsx
- src/components/layout/PanelChange/styles.module.scss
- src/containers/main/InvestContainer/index.tsx
Add Total Streams count to solve #43
> Add Total Streams count to solve #43 

- src/components/layout/UserSettings/index.tsx
Fix doc and whitepaper links which were inverted
> Fix doc and whitepaper links which were inverted

- src/components/layout/CoinRateForm/styles.module.scss
- src/components/layout/PanelChange/index.tsx
Fix coin_rate form closing on mobile when user clicked input
100$ bounty from shepardblue on the discord forum
> Fix coin_rate form closing on mobile when user clicked input

- src/components/layout/CoinBalance/index.tsx
- src/components/layout/UpgradeDowngradeButtons/index.tsx
- src/components/layout/UpgradeDowngradeButtons/styles.module.scss
- src/components/layout/UpgradePanel/index.tsx
Solve #70 
Remove Max button, and instead, fill the balance field with the max available amount when the user clicks its balance.
> Set Max on balance click to solve #70

- src/store/main/sagas/approveSaga.ts
- src/store/main/sagas/checkIfApprove.ts
- src/store/main/sagas/loadData.ts
- src/store/main/sagas/upgradeSaga.ts
Was checking allowance against balance of supertoken instead of underlying token.
Plus added function calls to sushi/wmatic
```js
// const hasApprove = Number(amount) > Number(balances && balances[superTokenAddress]);
const hasApprove = Number(amount) > Number(balances && balances[tokenAddress]);
```
> Bugfix: Upgrade Approval

- .eslintrc.js
- src/store/main/sagas/checkIfApprove.ts
Fix decimals in checkIfApprove
> Fix decimals in checkIfApprove

- src/components/layout/PanelChange/index.tsx
- src/constants/flowConfig.ts
- src/containers/main/InvestContainer/index.tsx
Solves #90 
Add a section under personal Flow indicating "Runs out on ..." where the date is given in LocaleString. Takes the overall outgoing streams of each market, use balance and current date to estimate when the steam will run out.
> Stream end date

- src/containers/main/HeaderContainer/index.tsx
- src/containers/main/HeaderContainer/styles.module.scss
reduced the space the header takes on mobile phone
> Reduce header height on mobile

- src/components/layout/CoinRateForm/index.tsx
Update Security deposit to be 4 hours of stream value
> Update Security deposit: is 4 hours of stream

- src/components/common/Price/index.tsx
moved from 6 decimals to two decimals.
> two decimal places

- src/api/ethereum.ts
- src/components/common/LpAPY/index.tsx
- src/components/layout/PanelChange/index.tsx
- src/i18n/en/main.json
- src/store/main/sagas/checkIfApprove.ts
- src/store/main/sagas/sweepQueryFlow.ts
- src/store/main/types.ts
Perf improvement: optimizing sushi APY requests
Only called once now the endpoints matic-minichef, price and matic-exchange
Solves https://github.com/Ricochet-Exchange/ricochet-frontend/issues/103
Also adds RIC rewards end date to finish https://github.com/Ricochet-Exchange/ricochet-frontend/issues/91
Plus some cleanup
> Perf improvement (sushi APY requests) + RIC rewards end date

- src/components/common/LpAPY/styles.module.scss
- src/components/common/Price/styles.module.scss
- src/components/common/WalletButton/styles.module.scss
- src/components/layout/PanelChange/index.tsx
- src/components/layout/PanelChange/styles.module.scss
Cleaned up market views on mobile
> Cleaned up market views on mobile

- src/components/common/ButtonNew/index.tsx
- src/components/common/Loader/index.tsx
- src/components/common/WalletButton/index.tsx
- src/components/layout/CoinRateForm/index.tsx
- src/components/layout/UpgradeDowngradeButtons/index.tsx
loading animation when transactions are pending
> loading animation

- src/containers/main/UpgradeContainer/styles.module.scss
Fix box shadow and the issue henceforth
> Fix the box shadow

- src/containers/main/UpgradeContainer/index.tsx
- src/containers/main/UpgradeContainer/styles.module.scss
> Move market prices below balance in Invest page

- src/containers/main/UpgradeContainer/styles.module.scss
> Add token balances to the mobile view in Upgrade page

- src/utils/getQueryGrath.ts
Increased limit from 100 on flows to 1000 (Maximum supported by Graph atm)
> Increased the limit on graph query

- src/assets/fonts/fontello/css/fontello-codes.css
- src/assets/fonts/fontello/css/fontello-embedded.css
- src/assets/fonts/fontello/css/fontello-ie7-codes.css
- src/assets/fonts/fontello/css/fontello-ie7.css
- src/assets/fonts/fontello/css/fontello.css
- src/components/common/FontIcon/index.tsx
- src/components/layout/InvestNav/index.tsx
> Tutorial button #166 

- package.json
- src/components/layout/UserSettings/index.tsx
- src/hooks/useENS.ts
- yarn.lock
> feat: add ens name support

- src/constants/flowConfig.ts
- src/containers/main/InvestContainer/index.tsx
> Moving ETHDAI market up and hiding subsidies if expired

- src/components/layout/UserSettings/styles.module.scss
Provides users with feedback when user hovers over each item through background color change.
Wraps both title and description with <a> tag to ease navigation for user.
> Improved user settings dropdown

- src/components/layout/InvestNav/index.tsx
- src/components/layout/InvestNav/styles.module.scss
- src/components/layout/UserSettings/index.tsx
- src/components/layout/UserSettings/styles.module.scss
- src/containers/MainLayout/styles.module.scss
- src/containers/main/HeaderContainer/index.tsx
- src/containers/main/HeaderContainer/styles.module.scss
- src/containers/main/InvestContainer/index.tsx
- src/containers/main/InvestContainer/styles.module.scss
- src/containers/main/UpgradeContainer/index.tsx
- src/pages/BanksPage/styles.module.scss
- src/pages/InvestPage/styles.module.scss
- src/pages/VaultPage/styles.module.scss
- src/pages/WalletPage/index.tsx
- src/pages/WalletPage/styles.module.scss
> Fixed linting issues.

- src/components/layout/InvestNav/index.tsx
- src/containers/main/HeaderContainer/index.tsx
- src/containers/main/HeaderContainer/styles.module.scss
- src/pages/WalletPage/styles.module.scss
Changes made:
1. Moved logo to header wrapper from nav wrapper
2. Decreased Padding on header wrapper
3.  Removed ( ) from wallet section in Nav
> Nav UI update

- src/components/common/WalletButton/index.tsx
- src/components/common/WalletButton/styles.module.scss
- src/components/layout/UserSettings/index.tsx
- src/hooks/useENS.ts
> Add ENS avatar support

- CONTRIBUTING.md
> chore: add contributor guide

- src/components/layout/UserSettings/index.tsx
- src/components/layout/UserSettings/styles.module.scss
> fix: border radius issue in menu dropdown for first and last item

- CODE_OF_CONDUCT.md
> feat: create CODE_OF_CONDUCT.md

- src/components/common/WalletButton/index.tsx
- src/components/layout/UserSettings/index.tsx
- src/hooks/useENS.ts
> fix: ens name rendering issue

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
> feat: add issue templates

- src/api/ethereum.ts
Made changes to make sure two market listitng is functional from frontend.
> Two Way Market Frontend Functional

- src/components/layout/UserSettings/styles.module.scss
> fix: center align menu button

- src/components/layout/InvestNav/index.tsx
- src/components/layout/InvestNav/styles.module.scss
- Increased font size
- Increased icon size
- Font will be bold while active
> chore: improve sidebar

- src/containers/main/InvestContainer/index.tsx
- src/containers/main/InvestContainer/styles.module.scss
- src/i18n/en/main.json
https://user-images.githubusercontent.com/69431456/152718156-1c7a78dd-2c31-4194-a2ce-349e302bc59e.mov
> feat: add empty state

- src/api/ethereum.ts
- src/constants/flowConfig.ts
> change to v2 listing

- SECURITY.md
Closes https://github.com/Ricochet-Exchange/ricochet-frontend/issues/348
> chore: add SECURITY.md doc

- src/constants/polygon_config.js
Fixes #NA
- Switch the USDC<>WBTC market address to a market using Quickswap for WBTC liquidity
> changed USDC<>WBTC market address

- src/components/layout/CoinChange/index.tsx
- src/components/layout/CoinChange/styles.module.scss
> fix: remove buggy button on token logo which affect the UI

- src/containers/main/UpgradeContainer/index.tsx
- src/containers/main/UpgradeContainer/styles.module.scss
> alignment fix for currency item

- src/components/common/WalletButton/index.tsx
- src/components/common/WalletButton/styles.module.scss
> feat: improve account button and add logout

- src/components/banks/ApproveToken/styles.module.scss
- src/components/banks/VaultActions/index.tsx
- src/components/banks/VaultActions/styles.module.scss
- src/components/banks/VaultDetails/styles.module.scss
- src/components/banks/VaultTransaction/index.tsx
- src/components/banks/VaultTransaction/styles.module.scss
- src/components/layout/InvestNav/index.tsx
- src/components/layout/PanelChange/index.tsx
- src/containers/main/BanksContainer/styles.module.scss
- src/containers/main/VaultsContainer/styles.module.scss
- src/utils/blockInvalidChars.ts
Fixes #
-Positions of buttons fixed
-Block buttons for users that don't give allowance
-Block Negative numbers from being place into input field  (user can put letters but the pay button won't work for them)
-Changed casing on buttons
-applied changes to mobile
> Vault style fixes

- src/components/common/AddressLink/styles.module.scss
- src/components/layout/InvestNav/index.tsx
- src/components/layout/InvestNav/styles.module.scss
- src/components/layout/PanelChange/styles.module.scss
- src/containers/main/UpgradeContainer/index.tsx
> enhancement: minor UI tweaks

- src/components/Hamburger/index.tsx
- src/components/Hamburger/styles.module.scss
- src/components/layout/MobileMenu/index.tsx
- src/components/layout/MobileMenu/styles.module.scss
- src/containers/main/HeaderContainer/index.tsx
- src/containers/main/HeaderContainer/styles.module.scss
Fixes #413 
https://user-images.githubusercontent.com/55599878/154504779-35d9c174-1604-4b5f-9c7b-5db5e360fdb3.mov
> feat: navbar revamp

- src/components/common/WalletButton/styles.module.scss
- src/components/layout/UpgradePanel/styles.module.scss
- src/components/layout/UserSettings/styles.module.scss
- src/containers/main/HeaderContainer/index.tsx
- src/containers/main/InvestContainer/index.tsx
- src/containers/main/InvestContainer/styles.module.scss
- src/containers/main/VaultsContainer/styles.module.scss
Fixes #436 
looks so much better now ❤️
> improve ui

- src/containers/main/UpgradeContainer/index.tsx
> feat: add supertoken portfolio balance

- src/components/layout/PanelChange/index.tsx
- src/components/layout/PanelChange/styles.module.scss
> fix: total flow rate shown twice on mobile

- src/components/common/AddressLink/styles.module.scss
- src/components/layout/CoinChange/styles.module.scss
- src/components/layout/PanelChange/styles.module.scss
- src/containers/main/InvestContainer/index.tsx
- src/containers/main/InvestContainer/styles.module.scss
Fixes #377
- I have modified some CSS classes to make the table headers align properly with the table row contents
https://user-images.githubusercontent.com/42779114/154859249-90d09d09-a082-4538-9ac2-b9e81fb14e50.mov
> CSS to properly align grid headers with grid row contents as in issue

- src/components/common/LoadingPopUp/index.tsx
- src/components/common/LoadingPopUp/styles.module.scss
- src/components/common/LoadingWrapper/index.tsx
- src/components/common/LoadingWrapper/styles.module.scss
- src/containers/main/BanksContainer/index.tsx
- src/containers/main/BanksContainer/styles.module.scss
- src/containers/main/VaultsContainer/index.tsx
- src/containers/main/VaultsContainer/styles.module.scss
Fixes #
- Changed Vault container to fetch data without user visiting bank page 
- Changed Bank and Vault pages to include LoadingPopUp
- Created LoadingPopUp comment
This PR is for the issue: https://github.com/Ricochet-Exchange/ricochet-frontend/issues/339
> Loading Page for Rexvault/bank

- src/api/ethereum.ts
Partial Fix for #429
- Scale the flow rate to work with the contracts requirements for rates (i.e. rounded to 1e12)
> Scale amount in start flow

- src/components/layout/CoinRateForm/index.tsx
Fixes #464
https://user-images.githubusercontent.com/69431456/155071194-c90d01ff-90cf-4dd9-827d-181a3e552e72.mov
> fix: don't allow to do start stream when amount is empty

- .eslintrc.js
- package.json
- src/components/layout/PanelChange/index.tsx
- src/containers/main/UpgradeContainer/index.tsx
- src/containers/main/UpgradeContainer/styles.module.scss
- yarn.lock
Fixes #462 
invest page -
https://user-images.githubusercontent.com/55599878/155354293-efb5e27c-8eac-4103-8a68-0b4905d82514.mov
https://user-images.githubusercontent.com/55599878/155354268-b4c07fa8-2bb3-4cb0-a7cf-783610bead33.mov
wallet page -
https://user-images.githubusercontent.com/55599878/155354306-7eb17997-078c-465d-bbbd-2f61237571e4.mov
https://user-images.githubusercontent.com/55599878/155354325-de8eaab8-2742-44ed-b8bf-ba9bbf338071.mov
launchpad page -
https://user-images.githubusercontent.com/55599878/155354302-d4bbac30-c0b9-44d5-80fc-d6a22e2f6584.mov
> feat: loading skeletons and improve cards

- package.json
- src/store/main/sagas/connectWeb3Modal.ts
- yarn.lock
> feat: add torus wallet support

- src/components/Hamburger/styles.module.scss
- src/components/common/AddressLink/styles.module.scss
- src/components/common/Price/styles.module.scss
- src/components/layout/MobileMenu/styles.module.scss
- src/components/layout/PanelChange/styles.module.scss
- src/containers/main/HeaderContainer/styles.module.scss
- src/containers/main/UpgradeContainer/index.tsx
> fix ui issues

- src/components/banks/BankDetails/index.tsx
- src/components/banks/BankDetails/styles.module.scss
- src/components/layout/UserSettings/styles.module.scss
- src/containers/main/UpgradeContainer/index.tsx
> fix ui bugs

- src/assets/styles/main.scss
- src/components/common/TextInput/index.tsx
- src/components/common/TextInput/styles.module.scss
- src/containers/main/HeaderContainer/styles.module.scss
> fix: UI issues listed in #484

- src/components/layout/PanelChange/index.tsx
> Bring back $

- src/containers/main/UpgradeContainer/index.tsx
- src/utils/getLastDistributions.ts
Fixes #
Removed comma requested in #493
> removed comma

- src/components/layout/InvestNav/index.tsx
- src/components/layout/MobileMenu/index.tsx
- src/containers/main/UpgradeContainer/index.tsx
- src/utils/getLastDistributions.ts
Fixes #
- Added Link button to mobile menu
- Added Link button to desktop invest nav
- Link currently takes no where because we haven't changed versions yet
> Add v1 link

- src/utils/getLastDistributions.ts
> UI freeze, wrong function call

- src/components/layout/UpgradeDowngradeButtons/index.tsx
> Fix regression on wallet page

- src/components/layout/InvestNav/index.tsx
> Fix v1 link

- .github/workflows/create-update-pr-env.yml
- .github/workflows/destroy-pr-env.yml
Fixes #
- ignore creation of ci env for dependabot branches
> Ignore dependabot ci

- src/components/layout/CoinRateForm/index.tsx
- src/components/layout/PanelChange/index.tsx
- src/containers/main/InvestContainer/index.tsx
> fix overlay issue
